/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.rythmml.ide;

import fr.unice.polytech.dsl.rythmml.ide.AbstractRymlIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RymlIdeModule extends AbstractRymlIdeModule {
}
