/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.rythmml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.unice.polytech.dsl.rythmml.RymlRuntimeModule;
import fr.unice.polytech.dsl.rythmml.RymlStandaloneSetup;
import fr.unice.polytech.dsl.rythmml.ide.RymlIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RymlIdeSetup extends RymlStandaloneSetup {
  @Override
  public Injector createInjector() {
    RymlRuntimeModule _rymlRuntimeModule = new RymlRuntimeModule();
    RymlIdeModule _rymlIdeModule = new RymlIdeModule();
    return Guice.createInjector(Modules2.mixin(_rymlRuntimeModule, _rymlIdeModule));
  }
}
