/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.rythmml.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.dsl.rythmml.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RymlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.unice.polytech.dsl.rythmml.Ryml");
	}

}
