/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.rythmml;

import fr.unice.polytech.dsl.rythmml.RymlStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RymlStandaloneSetup extends RymlStandaloneSetupGenerated {
  public static void doSetup() {
    new RymlStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
