/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.rythmml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RymlStandaloneSetup extends RymlStandaloneSetupGenerated {

	def static void doSetup() {
		new RymlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
