/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.rythmml.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RymlGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MusicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Music");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMusicKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTitleKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTitleAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTitleEStringParserRuleCall_3_1_0 = (RuleCall)cTitleAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAuthorKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAuthorAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAuthorEStringParserRuleCall_4_1_0 = (RuleCall)cAuthorAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBpmKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBpmAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBpmEIntParserRuleCall_5_1_0 = (RuleCall)cBpmAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cResolutionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cResolutionPerSlideAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cResolutionPerSlideEIntParserRuleCall_6_1_0 = (RuleCall)cResolutionPerSlideAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cOwnedNotesAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cOwnedNotesNoteParserRuleCall_7_0_0 = (RuleCall)cOwnedNotesAssignment_7_0.eContents().get(0);
		private final Assignment cOwnedNotesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cOwnedNotesNoteParserRuleCall_7_1_0 = (RuleCall)cOwnedNotesAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Assignment cOwnedBeatsAssignment_8_0 = (Assignment)cGroup_8.eContents().get(0);
		private final RuleCall cOwnedBeatsBeatParserRuleCall_8_0_0 = (RuleCall)cOwnedBeatsAssignment_8_0.eContents().get(0);
		private final Assignment cOwnedBeatsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOwnedBeatsBeatParserRuleCall_8_1_0 = (RuleCall)cOwnedBeatsAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Assignment cOwnedBarsAssignment_9_0 = (Assignment)cGroup_9.eContents().get(0);
		private final RuleCall cOwnedBarsBarParserRuleCall_9_0_0 = (RuleCall)cOwnedBarsAssignment_9_0.eContents().get(0);
		private final Assignment cOwnedBarsAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cOwnedBarsBarParserRuleCall_9_1_0 = (RuleCall)cOwnedBarsAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Assignment cOwnedPatternsAssignment_10_0 = (Assignment)cGroup_10.eContents().get(0);
		private final RuleCall cOwnedPatternsPatternParserRuleCall_10_0_0 = (RuleCall)cOwnedPatternsAssignment_10_0.eContents().get(0);
		private final Assignment cOwnedPatternsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cOwnedPatternsPatternParserRuleCall_10_1_0 = (RuleCall)cOwnedPatternsAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cOwnedSectionsAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final RuleCall cOwnedSectionsSectionParserRuleCall_11_0_0 = (RuleCall)cOwnedSectionsAssignment_11_0.eContents().get(0);
		private final Assignment cOwnedSectionsAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cOwnedSectionsSectionParserRuleCall_11_1_0 = (RuleCall)cOwnedSectionsAssignment_11_1.eContents().get(0);
		
		//Music:
		//	'Music'
		//	name=EString
		//	':' ('title:' title=EString)? ('author:' author=EString)? ('bpm:' bpm=EInt)? ('resolution:' resolutionPerSlide=EInt)?
		//	(ownedNotes+=Note ownedNotes+=Note*)? (ownedBeats+=Beat ownedBeats+=Beat*)? (ownedBars+=Bar ownedBars+=Bar*)?
		//	(ownedPatterns+=Pattern ownedPatterns+=Pattern*)? (ownedSections+=Section ownedSections+=Section*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Music' name=EString ':' ('title:' title=EString)? ('author:' author=EString)? ('bpm:' bpm=EInt)? ('resolution:'
		//resolutionPerSlide=EInt)? (ownedNotes+=Note ownedNotes+=Note*)? (ownedBeats+=Beat ownedBeats+=Beat*)? (ownedBars+=Bar
		//ownedBars+=Bar*)? (ownedPatterns+=Pattern ownedPatterns+=Pattern*)? (ownedSections+=Section ownedSections+=Section*)?
		public Group getGroup() { return cGroup; }
		
		//'Music'
		public Keyword getMusicKeyword_0() { return cMusicKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//('title:' title=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'title:'
		public Keyword getTitleKeyword_3_0() { return cTitleKeyword_3_0; }
		
		//title=EString
		public Assignment getTitleAssignment_3_1() { return cTitleAssignment_3_1; }
		
		//EString
		public RuleCall getTitleEStringParserRuleCall_3_1_0() { return cTitleEStringParserRuleCall_3_1_0; }
		
		//('author:' author=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'author:'
		public Keyword getAuthorKeyword_4_0() { return cAuthorKeyword_4_0; }
		
		//author=EString
		public Assignment getAuthorAssignment_4_1() { return cAuthorAssignment_4_1; }
		
		//EString
		public RuleCall getAuthorEStringParserRuleCall_4_1_0() { return cAuthorEStringParserRuleCall_4_1_0; }
		
		//('bpm:' bpm=EInt)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'bpm:'
		public Keyword getBpmKeyword_5_0() { return cBpmKeyword_5_0; }
		
		//bpm=EInt
		public Assignment getBpmAssignment_5_1() { return cBpmAssignment_5_1; }
		
		//EInt
		public RuleCall getBpmEIntParserRuleCall_5_1_0() { return cBpmEIntParserRuleCall_5_1_0; }
		
		//('resolution:' resolutionPerSlide=EInt)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'resolution:'
		public Keyword getResolutionKeyword_6_0() { return cResolutionKeyword_6_0; }
		
		//resolutionPerSlide=EInt
		public Assignment getResolutionPerSlideAssignment_6_1() { return cResolutionPerSlideAssignment_6_1; }
		
		//EInt
		public RuleCall getResolutionPerSlideEIntParserRuleCall_6_1_0() { return cResolutionPerSlideEIntParserRuleCall_6_1_0; }
		
		//(ownedNotes+=Note ownedNotes+=Note*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//ownedNotes+=Note
		public Assignment getOwnedNotesAssignment_7_0() { return cOwnedNotesAssignment_7_0; }
		
		//Note
		public RuleCall getOwnedNotesNoteParserRuleCall_7_0_0() { return cOwnedNotesNoteParserRuleCall_7_0_0; }
		
		//ownedNotes+=Note*
		public Assignment getOwnedNotesAssignment_7_1() { return cOwnedNotesAssignment_7_1; }
		
		//Note
		public RuleCall getOwnedNotesNoteParserRuleCall_7_1_0() { return cOwnedNotesNoteParserRuleCall_7_1_0; }
		
		//(ownedBeats+=Beat ownedBeats+=Beat*)?
		public Group getGroup_8() { return cGroup_8; }
		
		//ownedBeats+=Beat
		public Assignment getOwnedBeatsAssignment_8_0() { return cOwnedBeatsAssignment_8_0; }
		
		//Beat
		public RuleCall getOwnedBeatsBeatParserRuleCall_8_0_0() { return cOwnedBeatsBeatParserRuleCall_8_0_0; }
		
		//ownedBeats+=Beat*
		public Assignment getOwnedBeatsAssignment_8_1() { return cOwnedBeatsAssignment_8_1; }
		
		//Beat
		public RuleCall getOwnedBeatsBeatParserRuleCall_8_1_0() { return cOwnedBeatsBeatParserRuleCall_8_1_0; }
		
		//(ownedBars+=Bar ownedBars+=Bar*)?
		public Group getGroup_9() { return cGroup_9; }
		
		//ownedBars+=Bar
		public Assignment getOwnedBarsAssignment_9_0() { return cOwnedBarsAssignment_9_0; }
		
		//Bar
		public RuleCall getOwnedBarsBarParserRuleCall_9_0_0() { return cOwnedBarsBarParserRuleCall_9_0_0; }
		
		//ownedBars+=Bar*
		public Assignment getOwnedBarsAssignment_9_1() { return cOwnedBarsAssignment_9_1; }
		
		//Bar
		public RuleCall getOwnedBarsBarParserRuleCall_9_1_0() { return cOwnedBarsBarParserRuleCall_9_1_0; }
		
		//(ownedPatterns+=Pattern ownedPatterns+=Pattern*)?
		public Group getGroup_10() { return cGroup_10; }
		
		//ownedPatterns+=Pattern
		public Assignment getOwnedPatternsAssignment_10_0() { return cOwnedPatternsAssignment_10_0; }
		
		//Pattern
		public RuleCall getOwnedPatternsPatternParserRuleCall_10_0_0() { return cOwnedPatternsPatternParserRuleCall_10_0_0; }
		
		//ownedPatterns+=Pattern*
		public Assignment getOwnedPatternsAssignment_10_1() { return cOwnedPatternsAssignment_10_1; }
		
		//Pattern
		public RuleCall getOwnedPatternsPatternParserRuleCall_10_1_0() { return cOwnedPatternsPatternParserRuleCall_10_1_0; }
		
		//(ownedSections+=Section ownedSections+=Section*)?
		public Group getGroup_11() { return cGroup_11; }
		
		//ownedSections+=Section
		public Assignment getOwnedSectionsAssignment_11_0() { return cOwnedSectionsAssignment_11_0; }
		
		//Section
		public RuleCall getOwnedSectionsSectionParserRuleCall_11_0_0() { return cOwnedSectionsSectionParserRuleCall_11_0_0; }
		
		//ownedSections+=Section*
		public Assignment getOwnedSectionsAssignment_11_1() { return cOwnedSectionsAssignment_11_1; }
		
		//Section
		public RuleCall getOwnedSectionsSectionParserRuleCall_11_1_0() { return cOwnedSectionsSectionParserRuleCall_11_1_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Section");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSectionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPatternsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cPatternsPatternCrossReference_3_0 = (CrossReference)cPatternsAssignment_3.eContents().get(0);
		private final RuleCall cPatternsPatternEStringParserRuleCall_3_0_1 = (RuleCall)cPatternsPatternCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVerticalLineKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPatternsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cPatternsPatternCrossReference_4_1_0 = (CrossReference)cPatternsAssignment_4_1.eContents().get(0);
		private final RuleCall cPatternsPatternEStringParserRuleCall_4_1_0_1 = (RuleCall)cPatternsPatternCrossReference_4_1_0.eContents().get(1);
		
		//Section:
		//	'Section'
		//	name=EString
		//	':'
		//	patterns+=[Pattern|EString] ("|" patterns+=[Pattern|EString])*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Section' name=EString ':' patterns+=[Pattern|EString] ("|" patterns+=[Pattern|EString])*
		public Group getGroup() { return cGroup; }
		
		//'Section'
		public Keyword getSectionKeyword_0() { return cSectionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//patterns+=[Pattern|EString]
		public Assignment getPatternsAssignment_3() { return cPatternsAssignment_3; }
		
		//[Pattern|EString]
		public CrossReference getPatternsPatternCrossReference_3_0() { return cPatternsPatternCrossReference_3_0; }
		
		//EString
		public RuleCall getPatternsPatternEStringParserRuleCall_3_0_1() { return cPatternsPatternEStringParserRuleCall_3_0_1; }
		
		//("|" patterns+=[Pattern|EString])*
		public Group getGroup_4() { return cGroup_4; }
		
		//"|"
		public Keyword getVerticalLineKeyword_4_0() { return cVerticalLineKeyword_4_0; }
		
		//patterns+=[Pattern|EString]
		public Assignment getPatternsAssignment_4_1() { return cPatternsAssignment_4_1; }
		
		//[Pattern|EString]
		public CrossReference getPatternsPatternCrossReference_4_1_0() { return cPatternsPatternCrossReference_4_1_0; }
		
		//EString
		public RuleCall getPatternsPatternEStringParserRuleCall_4_1_0_1() { return cPatternsPatternEStringParserRuleCall_4_1_0_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class PatternElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Pattern");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPatternKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBarsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBarsBarMultiplierParserRuleCall_3_0 = (RuleCall)cBarsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVerticalLineKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBarsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBarsBarMultiplierParserRuleCall_4_1_0 = (RuleCall)cBarsAssignment_4_1.eContents().get(0);
		
		//Pattern:
		//	'Pattern'
		//	name=EString
		//	':'
		//	bars+=BarMultiplier ("|" bars+=BarMultiplier)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Pattern' name=EString ':' bars+=BarMultiplier ("|" bars+=BarMultiplier)*
		public Group getGroup() { return cGroup; }
		
		//'Pattern'
		public Keyword getPatternKeyword_0() { return cPatternKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//bars+=BarMultiplier
		public Assignment getBarsAssignment_3() { return cBarsAssignment_3; }
		
		//BarMultiplier
		public RuleCall getBarsBarMultiplierParserRuleCall_3_0() { return cBarsBarMultiplierParserRuleCall_3_0; }
		
		//("|" bars+=BarMultiplier)*
		public Group getGroup_4() { return cGroup_4; }
		
		//"|"
		public Keyword getVerticalLineKeyword_4_0() { return cVerticalLineKeyword_4_0; }
		
		//bars+=BarMultiplier
		public Assignment getBarsAssignment_4_1() { return cBarsAssignment_4_1; }
		
		//BarMultiplier
		public RuleCall getBarsBarMultiplierParserRuleCall_4_1_0() { return cBarsBarMultiplierParserRuleCall_4_1_0; }
	}
	public class BarMultiplierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.BarMultiplier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBarMultiplierAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cBarAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cBarBarCrossReference_1_0 = (CrossReference)cBarAssignment_1.eContents().get(0);
		private final RuleCall cBarBarEStringParserRuleCall_1_0_1 = (RuleCall)cBarBarCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cXKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cMultiplierAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMultiplierEIntParserRuleCall_2_1_0 = (RuleCall)cMultiplierAssignment_2_1.eContents().get(0);
		
		//BarMultiplier:
		//	{BarMultiplier} bar=[Bar|EString] ('x' multiplier=EInt)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{BarMultiplier} bar=[Bar|EString] ('x' multiplier=EInt)?
		public Group getGroup() { return cGroup; }
		
		//{BarMultiplier}
		public Action getBarMultiplierAction_0() { return cBarMultiplierAction_0; }
		
		//bar=[Bar|EString]
		public Assignment getBarAssignment_1() { return cBarAssignment_1; }
		
		//[Bar|EString]
		public CrossReference getBarBarCrossReference_1_0() { return cBarBarCrossReference_1_0; }
		
		//EString
		public RuleCall getBarBarEStringParserRuleCall_1_0_1() { return cBarBarEStringParserRuleCall_1_0_1; }
		
		//('x' multiplier=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'x'
		public Keyword getXKeyword_2_0() { return cXKeyword_2_0; }
		
		//multiplier=EInt
		public Assignment getMultiplierAssignment_2_1() { return cMultiplierAssignment_2_1; }
		
		//EInt
		public RuleCall getMultiplierEIntParserRuleCall_2_1_0() { return cMultiplierEIntParserRuleCall_2_1_0; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Operation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNoteAdditionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cNoteDeletionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNoteReplacementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Operation:
		//	NoteAddition | NoteDeletion | NoteReplacement;
		@Override public ParserRule getRule() { return rule; }
		
		//NoteAddition | NoteDeletion | NoteReplacement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NoteAddition
		public RuleCall getNoteAdditionParserRuleCall_0() { return cNoteAdditionParserRuleCall_0; }
		
		//NoteDeletion
		public RuleCall getNoteDeletionParserRuleCall_1() { return cNoteDeletionParserRuleCall_1; }
		
		//NoteReplacement
		public RuleCall getNoteReplacementParserRuleCall_2() { return cNoteReplacementParserRuleCall_2; }
	}
	public class NoteAdditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.NoteAddition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cBeatKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cBeatNumberAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cBeatNumberEIntParserRuleCall_0_1_0 = (RuleCall)cBeatNumberAssignment_0_1.eContents().get(0);
		private final Keyword cAddKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNoteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cNoteNoteCrossReference_2_0 = (CrossReference)cNoteAssignment_2.eContents().get(0);
		private final RuleCall cNoteNoteEStringParserRuleCall_2_0_1 = (RuleCall)cNoteNoteCrossReference_2_0.eContents().get(1);
		private final Keyword cAtTickKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDivisionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDivisionEIntParserRuleCall_4_0 = (RuleCall)cDivisionAssignment_4.eContents().get(0);
		
		//NoteAddition:
		//	('beat' beatNumber=EInt)? 'add' note=[Note|EString] 'at tick' division=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//('beat' beatNumber=EInt)? 'add' note=[Note|EString] 'at tick' division=EInt
		public Group getGroup() { return cGroup; }
		
		//('beat' beatNumber=EInt)?
		public Group getGroup_0() { return cGroup_0; }
		
		//'beat'
		public Keyword getBeatKeyword_0_0() { return cBeatKeyword_0_0; }
		
		//beatNumber=EInt
		public Assignment getBeatNumberAssignment_0_1() { return cBeatNumberAssignment_0_1; }
		
		//EInt
		public RuleCall getBeatNumberEIntParserRuleCall_0_1_0() { return cBeatNumberEIntParserRuleCall_0_1_0; }
		
		//'add'
		public Keyword getAddKeyword_1() { return cAddKeyword_1; }
		
		//note=[Note|EString]
		public Assignment getNoteAssignment_2() { return cNoteAssignment_2; }
		
		//[Note|EString]
		public CrossReference getNoteNoteCrossReference_2_0() { return cNoteNoteCrossReference_2_0; }
		
		//EString
		public RuleCall getNoteNoteEStringParserRuleCall_2_0_1() { return cNoteNoteEStringParserRuleCall_2_0_1; }
		
		//'at tick'
		public Keyword getAtTickKeyword_3() { return cAtTickKeyword_3; }
		
		//division=EInt
		public Assignment getDivisionAssignment_4() { return cDivisionAssignment_4; }
		
		//EInt
		public RuleCall getDivisionEIntParserRuleCall_4_0() { return cDivisionEIntParserRuleCall_4_0; }
	}
	public class NoteDeletionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.NoteDeletion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cBeatKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cBeatNumberAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cBeatNumberEIntParserRuleCall_0_1_0 = (RuleCall)cBeatNumberAssignment_0_1.eContents().get(0);
		private final Keyword cDeleteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNoteAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cNoteNoteCrossReference_2_0 = (CrossReference)cNoteAssignment_2.eContents().get(0);
		private final RuleCall cNoteNoteEStringParserRuleCall_2_0_1 = (RuleCall)cNoteNoteCrossReference_2_0.eContents().get(1);
		
		//NoteDeletion:
		//	('beat' beatNumber=EInt)? 'delete' note=[Note|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//('beat' beatNumber=EInt)? 'delete' note=[Note|EString]
		public Group getGroup() { return cGroup; }
		
		//('beat' beatNumber=EInt)?
		public Group getGroup_0() { return cGroup_0; }
		
		//'beat'
		public Keyword getBeatKeyword_0_0() { return cBeatKeyword_0_0; }
		
		//beatNumber=EInt
		public Assignment getBeatNumberAssignment_0_1() { return cBeatNumberAssignment_0_1; }
		
		//EInt
		public RuleCall getBeatNumberEIntParserRuleCall_0_1_0() { return cBeatNumberEIntParserRuleCall_0_1_0; }
		
		//'delete'
		public Keyword getDeleteKeyword_1() { return cDeleteKeyword_1; }
		
		//note=[Note|EString]
		public Assignment getNoteAssignment_2() { return cNoteAssignment_2; }
		
		//[Note|EString]
		public CrossReference getNoteNoteCrossReference_2_0() { return cNoteNoteCrossReference_2_0; }
		
		//EString
		public RuleCall getNoteNoteEStringParserRuleCall_2_0_1() { return cNoteNoteEStringParserRuleCall_2_0_1; }
	}
	public class NoteReplacementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.NoteReplacement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Keyword cBeatKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Assignment cBeatNumberAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cBeatNumberEIntParserRuleCall_0_1_0 = (RuleCall)cBeatNumberAssignment_0_1.eContents().get(0);
		private final Keyword cReplaceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNoteSrcAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cNoteSrcNoteCrossReference_2_0 = (CrossReference)cNoteSrcAssignment_2.eContents().get(0);
		private final RuleCall cNoteSrcNoteEStringParserRuleCall_2_0_1 = (RuleCall)cNoteSrcNoteCrossReference_2_0.eContents().get(1);
		private final Keyword cByKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNewNoteAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cNewNoteNoteCrossReference_4_0 = (CrossReference)cNewNoteAssignment_4.eContents().get(0);
		private final RuleCall cNewNoteNoteEStringParserRuleCall_4_0_1 = (RuleCall)cNewNoteNoteCrossReference_4_0.eContents().get(1);
		
		//NoteReplacement:
		//	('beat' beatNumber=EInt)? 'replace' noteSrc=[Note|EString] 'by' newNote=[Note|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//('beat' beatNumber=EInt)? 'replace' noteSrc=[Note|EString] 'by' newNote=[Note|EString]
		public Group getGroup() { return cGroup; }
		
		//('beat' beatNumber=EInt)?
		public Group getGroup_0() { return cGroup_0; }
		
		//'beat'
		public Keyword getBeatKeyword_0_0() { return cBeatKeyword_0_0; }
		
		//beatNumber=EInt
		public Assignment getBeatNumberAssignment_0_1() { return cBeatNumberAssignment_0_1; }
		
		//EInt
		public RuleCall getBeatNumberEIntParserRuleCall_0_1_0() { return cBeatNumberEIntParserRuleCall_0_1_0; }
		
		//'replace'
		public Keyword getReplaceKeyword_1() { return cReplaceKeyword_1; }
		
		//noteSrc=[Note|EString]
		public Assignment getNoteSrcAssignment_2() { return cNoteSrcAssignment_2; }
		
		//[Note|EString]
		public CrossReference getNoteSrcNoteCrossReference_2_0() { return cNoteSrcNoteCrossReference_2_0; }
		
		//EString
		public RuleCall getNoteSrcNoteEStringParserRuleCall_2_0_1() { return cNoteSrcNoteEStringParserRuleCall_2_0_1; }
		
		//'by'
		public Keyword getByKeyword_3() { return cByKeyword_3; }
		
		//newNote=[Note|EString]
		public Assignment getNewNoteAssignment_4() { return cNewNoteAssignment_4; }
		
		//[Note|EString]
		public CrossReference getNewNoteNoteCrossReference_4_0() { return cNewNoteNoteCrossReference_4_0; }
		
		//EString
		public RuleCall getNewNoteNoteEStringParserRuleCall_4_0_1() { return cNewNoteNoteEStringParserRuleCall_4_0_1; }
	}
	public class BarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Bar");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cClassicalBarParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cModifiedBarParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Bar:
		//	ClassicalBar | ModifiedBar;
		@Override public ParserRule getRule() { return rule; }
		
		//ClassicalBar | ModifiedBar
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ClassicalBar
		public RuleCall getClassicalBarParserRuleCall_0() { return cClassicalBarParserRuleCall_0; }
		
		//ModifiedBar
		public RuleCall getModifiedBarParserRuleCall_1() { return cModifiedBarParserRuleCall_1; }
	}
	public class ClassicalBarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.ClassicalBar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassicalBarAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBarKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBeatsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cBeatsBeatCrossReference_4_0 = (CrossReference)cBeatsAssignment_4.eContents().get(0);
		private final RuleCall cBeatsBeatEStringParserRuleCall_4_0_1 = (RuleCall)cBeatsBeatCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cVerticalLineKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBeatsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cBeatsBeatCrossReference_5_1_0 = (CrossReference)cBeatsAssignment_5_1.eContents().get(0);
		private final RuleCall cBeatsBeatEStringParserRuleCall_5_1_0_1 = (RuleCall)cBeatsBeatCrossReference_5_1_0.eContents().get(1);
		
		//ClassicalBar:
		//	{ClassicalBar}
		//	'Bar' name=EString ':' beats+=[Beat|EString] ("|" beats+=[Beat|EString])*;
		@Override public ParserRule getRule() { return rule; }
		
		//{ClassicalBar} 'Bar' name=EString ':' beats+=[Beat|EString] ("|" beats+=[Beat|EString])*
		public Group getGroup() { return cGroup; }
		
		//{ClassicalBar}
		public Action getClassicalBarAction_0() { return cClassicalBarAction_0; }
		
		//'Bar'
		public Keyword getBarKeyword_1() { return cBarKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//beats+=[Beat|EString]
		public Assignment getBeatsAssignment_4() { return cBeatsAssignment_4; }
		
		//[Beat|EString]
		public CrossReference getBeatsBeatCrossReference_4_0() { return cBeatsBeatCrossReference_4_0; }
		
		//EString
		public RuleCall getBeatsBeatEStringParserRuleCall_4_0_1() { return cBeatsBeatEStringParserRuleCall_4_0_1; }
		
		//("|" beats+=[Beat|EString])*
		public Group getGroup_5() { return cGroup_5; }
		
		//"|"
		public Keyword getVerticalLineKeyword_5_0() { return cVerticalLineKeyword_5_0; }
		
		//beats+=[Beat|EString]
		public Assignment getBeatsAssignment_5_1() { return cBeatsAssignment_5_1; }
		
		//[Beat|EString]
		public CrossReference getBeatsBeatCrossReference_5_1_0() { return cBeatsBeatCrossReference_5_1_0; }
		
		//EString
		public RuleCall getBeatsBeatEStringParserRuleCall_5_1_0_1() { return cBeatsBeatEStringParserRuleCall_5_1_0_1; }
	}
	public class ModifiedBarElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.ModifiedBar");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModifiedBarAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBarKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cBasedOnKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBarAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cBarBarCrossReference_4_0 = (CrossReference)cBarAssignment_4.eContents().get(0);
		private final RuleCall cBarBarEStringParserRuleCall_4_0_1 = (RuleCall)cBarBarCrossReference_4_0.eContents().get(1);
		private final Keyword cModificationsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cHyphenMinusKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cOperationsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cOperationsOperationParserRuleCall_7_0 = (RuleCall)cOperationsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cHyphenMinusKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cOperationsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_8_1_0 = (RuleCall)cOperationsAssignment_8_1.eContents().get(0);
		
		//ModifiedBar:
		//	{ModifiedBar}
		//	'Bar' name=EString 'based on' bar=[Bar|EString]
		//	'modifications:'
		//	'-' operations+=Operation ('-' operations+=Operation)*;
		@Override public ParserRule getRule() { return rule; }
		
		//{ModifiedBar} 'Bar' name=EString 'based on' bar=[Bar|EString] 'modifications:' '-' operations+=Operation ('-'
		//operations+=Operation)*
		public Group getGroup() { return cGroup; }
		
		//{ModifiedBar}
		public Action getModifiedBarAction_0() { return cModifiedBarAction_0; }
		
		//'Bar'
		public Keyword getBarKeyword_1() { return cBarKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'based on'
		public Keyword getBasedOnKeyword_3() { return cBasedOnKeyword_3; }
		
		//bar=[Bar|EString]
		public Assignment getBarAssignment_4() { return cBarAssignment_4; }
		
		//[Bar|EString]
		public CrossReference getBarBarCrossReference_4_0() { return cBarBarCrossReference_4_0; }
		
		//EString
		public RuleCall getBarBarEStringParserRuleCall_4_0_1() { return cBarBarEStringParserRuleCall_4_0_1; }
		
		//'modifications:'
		public Keyword getModificationsKeyword_5() { return cModificationsKeyword_5; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_6() { return cHyphenMinusKeyword_6; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_7() { return cOperationsAssignment_7; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_7_0() { return cOperationsOperationParserRuleCall_7_0; }
		
		//('-' operations+=Operation)*
		public Group getGroup_8() { return cGroup_8; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_8_0() { return cHyphenMinusKeyword_8_0; }
		
		//operations+=Operation
		public Assignment getOperationsAssignment_8_1() { return cOperationsAssignment_8_1; }
		
		//Operation
		public RuleCall getOperationsOperationParserRuleCall_8_1_0() { return cOperationsOperationParserRuleCall_8_1_0; }
	}
	public class BeatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Beat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBeatKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNbOfTicksKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTotalDivNumberAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTotalDivNumberEIntParserRuleCall_3_1_0 = (RuleCall)cTotalDivNumberAssignment_3_1.eContents().get(0);
		private final Assignment cNotesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cNotesNoteCrossReference_4_0 = (CrossReference)cNotesAssignment_4.eContents().get(0);
		private final RuleCall cNotesNoteEStringParserRuleCall_4_0_1 = (RuleCall)cNotesNoteCrossReference_4_0.eContents().get(1);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNotePositionsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNotePositionsEIntParserRuleCall_6_0 = (RuleCall)cNotePositionsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cVerticalLineKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cNotesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cNotesNoteCrossReference_7_1_0 = (CrossReference)cNotesAssignment_7_1.eContents().get(0);
		private final RuleCall cNotesNoteEStringParserRuleCall_7_1_0_1 = (RuleCall)cNotesNoteCrossReference_7_1_0.eContents().get(1);
		private final Keyword cCommaKeyword_7_2 = (Keyword)cGroup_7.eContents().get(2);
		private final Assignment cNotePositionsAssignment_7_3 = (Assignment)cGroup_7.eContents().get(3);
		private final RuleCall cNotePositionsEIntParserRuleCall_7_3_0 = (RuleCall)cNotePositionsAssignment_7_3.eContents().get(0);
		
		//Beat:
		//	'Beat' name=EString ':' ('Nb of ticks :' totalDivNumber=EInt)?
		//	notes+=[Note|EString] ',' notePositions+=EInt ("|" notes+=[Note|EString] ',' notePositions+=EInt)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'Beat' name=EString ':' ('Nb of ticks :' totalDivNumber=EInt)? notes+=[Note|EString] ',' notePositions+=EInt ("|"
		//notes+=[Note|EString] ',' notePositions+=EInt)*
		public Group getGroup() { return cGroup; }
		
		//'Beat'
		public Keyword getBeatKeyword_0() { return cBeatKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//('Nb of ticks :' totalDivNumber=EInt)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'Nb of ticks :'
		public Keyword getNbOfTicksKeyword_3_0() { return cNbOfTicksKeyword_3_0; }
		
		//totalDivNumber=EInt
		public Assignment getTotalDivNumberAssignment_3_1() { return cTotalDivNumberAssignment_3_1; }
		
		//EInt
		public RuleCall getTotalDivNumberEIntParserRuleCall_3_1_0() { return cTotalDivNumberEIntParserRuleCall_3_1_0; }
		
		//notes+=[Note|EString]
		public Assignment getNotesAssignment_4() { return cNotesAssignment_4; }
		
		//[Note|EString]
		public CrossReference getNotesNoteCrossReference_4_0() { return cNotesNoteCrossReference_4_0; }
		
		//EString
		public RuleCall getNotesNoteEStringParserRuleCall_4_0_1() { return cNotesNoteEStringParserRuleCall_4_0_1; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//notePositions+=EInt
		public Assignment getNotePositionsAssignment_6() { return cNotePositionsAssignment_6; }
		
		//EInt
		public RuleCall getNotePositionsEIntParserRuleCall_6_0() { return cNotePositionsEIntParserRuleCall_6_0; }
		
		//("|" notes+=[Note|EString] ',' notePositions+=EInt)*
		public Group getGroup_7() { return cGroup_7; }
		
		//"|"
		public Keyword getVerticalLineKeyword_7_0() { return cVerticalLineKeyword_7_0; }
		
		//notes+=[Note|EString]
		public Assignment getNotesAssignment_7_1() { return cNotesAssignment_7_1; }
		
		//[Note|EString]
		public CrossReference getNotesNoteCrossReference_7_1_0() { return cNotesNoteCrossReference_7_1_0; }
		
		//EString
		public RuleCall getNotesNoteEStringParserRuleCall_7_1_0_1() { return cNotesNoteEStringParserRuleCall_7_1_0_1; }
		
		//','
		public Keyword getCommaKeyword_7_2() { return cCommaKeyword_7_2; }
		
		//notePositions+=EInt
		public Assignment getNotePositionsAssignment_7_3() { return cNotePositionsAssignment_7_3; }
		
		//EInt
		public RuleCall getNotePositionsEIntParserRuleCall_7_3_0() { return cNotePositionsEIntParserRuleCall_7_3_0; }
	}
	public class NoteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.Note");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cNoteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cNoteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueDrumNoteValueEnumRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		
		//Note:
		//	{Note}
		//	'Note' name=EString ':' value=DrumNoteValue?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Note} 'Note' name=EString ':' value=DrumNoteValue?
		public Group getGroup() { return cGroup; }
		
		//{Note}
		public Action getNoteAction_0() { return cNoteAction_0; }
		
		//'Note'
		public Keyword getNoteKeyword_1() { return cNoteKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//value=DrumNoteValue?
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }
		
		//DrumNoteValue
		public RuleCall getValueDrumNoteValueEnumRuleCall_4_0() { return cValueDrumNoteValueEnumRuleCall_4_0; }
	}
	
	public class DrumNoteValueElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "fr.unice.polytech.dsl.rythmml.Ryml.DrumNoteValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSDSDKeyword_0_0 = (Keyword)cSDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBDBDKeyword_1_0 = (Keyword)cBDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cCHEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cCHCHKeyword_2_0 = (Keyword)cCHEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cOHEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cOHOHKeyword_3_0 = (Keyword)cOHEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCCEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCCCCKeyword_4_0 = (Keyword)cCCEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cRCEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cRCRCKeyword_5_0 = (Keyword)cRCEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cTMEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cTMTMKeyword_6_0 = (Keyword)cTMEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cTOEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cTOTOKeyword_7_0 = (Keyword)cTOEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cSEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cSSKeyword_8_0 = (Keyword)cSEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cWSEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cWSWSKeyword_9_0 = (Keyword)cWSEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cLEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cLLKeyword_10_0 = (Keyword)cLEnumLiteralDeclaration_10.eContents().get(0);
		
		//enum DrumNoteValue:
		//	SD | BD | CH | OH | CC | RC | TM | TO | S | WS | L;
		public EnumRule getRule() { return rule; }
		
		//SD | BD | CH | OH | CC | RC | TM | TO | S | WS | L
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SD
		public EnumLiteralDeclaration getSDEnumLiteralDeclaration_0() { return cSDEnumLiteralDeclaration_0; }
		
		//'SD'
		public Keyword getSDSDKeyword_0_0() { return cSDSDKeyword_0_0; }
		
		//BD
		public EnumLiteralDeclaration getBDEnumLiteralDeclaration_1() { return cBDEnumLiteralDeclaration_1; }
		
		//'BD'
		public Keyword getBDBDKeyword_1_0() { return cBDBDKeyword_1_0; }
		
		//CH
		public EnumLiteralDeclaration getCHEnumLiteralDeclaration_2() { return cCHEnumLiteralDeclaration_2; }
		
		//'CH'
		public Keyword getCHCHKeyword_2_0() { return cCHCHKeyword_2_0; }
		
		//OH
		public EnumLiteralDeclaration getOHEnumLiteralDeclaration_3() { return cOHEnumLiteralDeclaration_3; }
		
		//'OH'
		public Keyword getOHOHKeyword_3_0() { return cOHOHKeyword_3_0; }
		
		//CC
		public EnumLiteralDeclaration getCCEnumLiteralDeclaration_4() { return cCCEnumLiteralDeclaration_4; }
		
		//'CC'
		public Keyword getCCCCKeyword_4_0() { return cCCCCKeyword_4_0; }
		
		//RC
		public EnumLiteralDeclaration getRCEnumLiteralDeclaration_5() { return cRCEnumLiteralDeclaration_5; }
		
		//'RC'
		public Keyword getRCRCKeyword_5_0() { return cRCRCKeyword_5_0; }
		
		//TM
		public EnumLiteralDeclaration getTMEnumLiteralDeclaration_6() { return cTMEnumLiteralDeclaration_6; }
		
		//'TM'
		public Keyword getTMTMKeyword_6_0() { return cTMTMKeyword_6_0; }
		
		//TO
		public EnumLiteralDeclaration getTOEnumLiteralDeclaration_7() { return cTOEnumLiteralDeclaration_7; }
		
		//'TO'
		public Keyword getTOTOKeyword_7_0() { return cTOTOKeyword_7_0; }
		
		//S
		public EnumLiteralDeclaration getSEnumLiteralDeclaration_8() { return cSEnumLiteralDeclaration_8; }
		
		//'S'
		public Keyword getSSKeyword_8_0() { return cSSKeyword_8_0; }
		
		//WS
		public EnumLiteralDeclaration getWSEnumLiteralDeclaration_9() { return cWSEnumLiteralDeclaration_9; }
		
		//'WS'
		public Keyword getWSWSKeyword_9_0() { return cWSWSKeyword_9_0; }
		
		//L
		public EnumLiteralDeclaration getLEnumLiteralDeclaration_10() { return cLEnumLiteralDeclaration_10; }
		
		//'L'
		public Keyword getLLKeyword_10_0() { return cLLKeyword_10_0; }
	}
	
	private final MusicElements pMusic;
	private final EStringElements pEString;
	private final SectionElements pSection;
	private final EIntElements pEInt;
	private final PatternElements pPattern;
	private final BarMultiplierElements pBarMultiplier;
	private final OperationElements pOperation;
	private final NoteAdditionElements pNoteAddition;
	private final NoteDeletionElements pNoteDeletion;
	private final NoteReplacementElements pNoteReplacement;
	private final BarElements pBar;
	private final ClassicalBarElements pClassicalBar;
	private final ModifiedBarElements pModifiedBar;
	private final BeatElements pBeat;
	private final NoteElements pNote;
	private final DrumNoteValueElements eDrumNoteValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RymlGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMusic = new MusicElements();
		this.pEString = new EStringElements();
		this.pSection = new SectionElements();
		this.pEInt = new EIntElements();
		this.pPattern = new PatternElements();
		this.pBarMultiplier = new BarMultiplierElements();
		this.pOperation = new OperationElements();
		this.pNoteAddition = new NoteAdditionElements();
		this.pNoteDeletion = new NoteDeletionElements();
		this.pNoteReplacement = new NoteReplacementElements();
		this.pBar = new BarElements();
		this.pClassicalBar = new ClassicalBarElements();
		this.pModifiedBar = new ModifiedBarElements();
		this.pBeat = new BeatElements();
		this.pNote = new NoteElements();
		this.eDrumNoteValue = new DrumNoteValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("fr.unice.polytech.dsl.rythmml.Ryml".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Music:
	//	'Music'
	//	name=EString
	//	':' ('title:' title=EString)? ('author:' author=EString)? ('bpm:' bpm=EInt)? ('resolution:' resolutionPerSlide=EInt)?
	//	(ownedNotes+=Note ownedNotes+=Note*)? (ownedBeats+=Beat ownedBeats+=Beat*)? (ownedBars+=Bar ownedBars+=Bar*)?
	//	(ownedPatterns+=Pattern ownedPatterns+=Pattern*)? (ownedSections+=Section ownedSections+=Section*)?;
	public MusicElements getMusicAccess() {
		return pMusic;
	}
	
	public ParserRule getMusicRule() {
		return getMusicAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Section:
	//	'Section'
	//	name=EString
	//	':'
	//	patterns+=[Pattern|EString] ("|" patterns+=[Pattern|EString])*;
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Pattern:
	//	'Pattern'
	//	name=EString
	//	':'
	//	bars+=BarMultiplier ("|" bars+=BarMultiplier)*;
	public PatternElements getPatternAccess() {
		return pPattern;
	}
	
	public ParserRule getPatternRule() {
		return getPatternAccess().getRule();
	}
	
	//BarMultiplier:
	//	{BarMultiplier} bar=[Bar|EString] ('x' multiplier=EInt)?;
	public BarMultiplierElements getBarMultiplierAccess() {
		return pBarMultiplier;
	}
	
	public ParserRule getBarMultiplierRule() {
		return getBarMultiplierAccess().getRule();
	}
	
	//Operation:
	//	NoteAddition | NoteDeletion | NoteReplacement;
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//NoteAddition:
	//	('beat' beatNumber=EInt)? 'add' note=[Note|EString] 'at tick' division=EInt;
	public NoteAdditionElements getNoteAdditionAccess() {
		return pNoteAddition;
	}
	
	public ParserRule getNoteAdditionRule() {
		return getNoteAdditionAccess().getRule();
	}
	
	//NoteDeletion:
	//	('beat' beatNumber=EInt)? 'delete' note=[Note|EString];
	public NoteDeletionElements getNoteDeletionAccess() {
		return pNoteDeletion;
	}
	
	public ParserRule getNoteDeletionRule() {
		return getNoteDeletionAccess().getRule();
	}
	
	//NoteReplacement:
	//	('beat' beatNumber=EInt)? 'replace' noteSrc=[Note|EString] 'by' newNote=[Note|EString];
	public NoteReplacementElements getNoteReplacementAccess() {
		return pNoteReplacement;
	}
	
	public ParserRule getNoteReplacementRule() {
		return getNoteReplacementAccess().getRule();
	}
	
	//Bar:
	//	ClassicalBar | ModifiedBar;
	public BarElements getBarAccess() {
		return pBar;
	}
	
	public ParserRule getBarRule() {
		return getBarAccess().getRule();
	}
	
	//ClassicalBar:
	//	{ClassicalBar}
	//	'Bar' name=EString ':' beats+=[Beat|EString] ("|" beats+=[Beat|EString])*;
	public ClassicalBarElements getClassicalBarAccess() {
		return pClassicalBar;
	}
	
	public ParserRule getClassicalBarRule() {
		return getClassicalBarAccess().getRule();
	}
	
	//ModifiedBar:
	//	{ModifiedBar}
	//	'Bar' name=EString 'based on' bar=[Bar|EString]
	//	'modifications:'
	//	'-' operations+=Operation ('-' operations+=Operation)*;
	public ModifiedBarElements getModifiedBarAccess() {
		return pModifiedBar;
	}
	
	public ParserRule getModifiedBarRule() {
		return getModifiedBarAccess().getRule();
	}
	
	//Beat:
	//	'Beat' name=EString ':' ('Nb of ticks :' totalDivNumber=EInt)?
	//	notes+=[Note|EString] ',' notePositions+=EInt ("|" notes+=[Note|EString] ',' notePositions+=EInt)*;
	public BeatElements getBeatAccess() {
		return pBeat;
	}
	
	public ParserRule getBeatRule() {
		return getBeatAccess().getRule();
	}
	
	//Note:
	//	{Note}
	//	'Note' name=EString ':' value=DrumNoteValue?;
	public NoteElements getNoteAccess() {
		return pNote;
	}
	
	public ParserRule getNoteRule() {
		return getNoteAccess().getRule();
	}
	
	//enum DrumNoteValue:
	//	SD | BD | CH | OH | CC | RC | TM | TO | S | WS | L;
	public DrumNoteValueElements getDrumNoteValueAccess() {
		return eDrumNoteValue;
	}
	
	public EnumRule getDrumNoteValueRule() {
		return getDrumNoteValueAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
